version: '3'

services:
  db:
    env_file:
      - ./db-prod.env
    ports:
      - "5432:5432"
    image: postgres:latest
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  app:
    env_file:
      - ./monolith-prod.env
    build: .
    ports:
      - "8080:8080"
    working_dir: /opt/seapay
    command: >
      bash -c "wget https://gitlab.com/alexanderv21/seapay-microservice/-/jobs/artifacts/master/download?job=build -O /tmp/temp.zip &&
      unzip /tmp/temp.zip -d /tmp && rm /tmp/temp.zip && mv /tmp/pkg/* . &&
      ./migration.sh &&
      java -jar seapay-monolith.jar"
    depends_on:
      - db
    restart: always
